version: '3.8'

services:
  postgres:
    container_name: nome_container
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_forte
      POSTGRES_DB:
      PGDATA: /data/postgres
    volumes:
      - /data/pg:/data/postgres
